#ifndef SRC_PINS_H_INCLUDED
#define SRC_PINS_H_INCLUDED

#define STOCK_BUTTON_PIN          	2
#define STOCK_LED_PIN             	4

#define SECURITY_BUTTON_PIN       	5
#define SECURITY_LED_PIN          	18

#define BUZZER_PIN					32

#define WEIGHT_SENSOR_01_DT_PIN 	13
#define WEIGHT_SENSOR_01_SCK_PIN	12
#define WEIGHT_SENSOR_01_LED_PIN	14

#define WEIGHT_SENSOR_02_DT_PIN   	27
#define WEIGHT_SENSOR_02_SCK_PIN  	26
#define WEIGHT_SENSOR_02_LED_PIN  	25

#endif  // SRC_PINS_H_INCLUDED
